### ISSUE TITLE
Write a guide to loading our `firmware-esp32/` code onto an ESP32 Thing.

### ISSUE THREAD

**Issue by tcr** [tessel/reach-wg#17]
This should be straightforward; we have code in`firmware-esp32/` and we want an instructions file at `firmware-esp32/README.md` which describes how to load code onto the device.

This may increase in complexity over time, but for now can mostly replicate the instructions at <https://github.com/espressif/esp-idf-template>, e.g:

```
## Getting started

* Plug in your ESP32 Thing.
* Run the makefile.
* Load it onto the device.
* Expect $THIS_THING to happen.

### Troubleshooting

Possible errors with drivers? etc. Follow these instructions: $INSTRUCTIONS_URL
```

**Comment by tcr** [comment]
Great jaerb there, Homestar. @EvanSimpson

**Comment by Frijol** [comment]
closed in https://github.com/tessel/reach-wg/pull/19
